/ixcom/ixcom_driver_lc:                 # used by ixcom_driver_lc in the namespace ixcom
# /**:                                  # one fits all
  ros__parameters:
    ip:
      address: 127.0.0.1
    serial:
      ignore: true
      port: 1
      baud: 115200
      enable: true
    timestamp_mode: GPS
    imudata_mode: IMURAW
    qos: SYSTEMDEFAULTS
    leap_seconds: 18
    manual_local_tangential_plane:
      enable: false
      lon: 0.0
      lat: 0.0
      alt: 0.0
    magnetometer_scale_factor: 1.0000000116860974e-07
    topics:
      Imu:
        frequency_hz: 10
        remap_to: ""
      NavSatStatus:
        frequency_hz: 0
        remap_to: ""
      NavSatFix_GNSS:
        frequency_hz: 10
        remap_to: "NavSatFix"
      NavSatFix_INS:
        frequency_hz: 0
        remap_to: ""
      TimeReference:
        frequency_hz: 10
        remap_to: ""
      MagneticField:
        frequency_hz: 0
        remap_to: ""
      Odometry:
        frame_id: "enu"
        frequency_hz: 10
        remap_to: ""
      PoseWithCovarianceStamped:
        frequency_hz: 0
        remap_to: ""
      TwistStamped:
        frequency_hz: 10
        remap_to: ""

